name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use the latest stable version of Python 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown python-frontmatter

    - name: Run changelog updater
      run: |
        echo "Current directory contents:"
        ls -la
        echo "Running changelog_updater.py"
        if [ -f changelog_updater.py ]; then
          python changelog_updater.py
        else
          echo "Error: changelog_updater.py not found"
          exit 1
        fi

    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "::set-output name=changed::true"

    - name: Commit changes
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add CHANGELOG.md
        git commit -m "Update CHANGELOG.md [skip ci]"

    - name: Push changes
      if: steps.git-check.outputs.changed == 'true'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT_Token }}
        branch: ${{ github.ref_name }}

    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs/
      if: always()  # This ensures logs are uploaded even if the job fails