name: Update Changelog

on:
  push:
    branches:
      - main

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use the latest stable version of Python 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run changelog updater
      run: python changelog_updater.py

    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add CHANGELOG.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update CHANGELOG.md"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref_name }}

    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs/
      if: always()  # This ensures logs are uploaded even if the job fails